### PR TITLE
Create ShippingAddress.cs

### PR DESCRIPTION
**Pull request by baer999**
https://github.com/Viincenttt/MollieApi/issues/214

### CODE REVIEW

**Comment by Viincenttt** [comment]
Hi @baer999 ,

This pull request only contains the ShippingAddress.cs file, but without any references to it, it won't be used. Did you forget to add any other files? 

Kind regards,
Vincent

**Comment by baer999** [comment]
Hi @Viincenttt 
yes, like described in my issue...
It is my first pull request, so sorry for the un-knowledge...
changed the file in web because via git add / commit / push I got an "not authorized" with my user....

https://github.com/Viincenttt/MollieApi/issues/214

Does this help you?

**Comment by baer999** [comment]
@Viincenttt 
I updated the Pull Request in order that it can easily be used.
Let me know if this is fine and Kind regards.

**Comment by Viincenttt** [comment]
Hi @baer999 ,

Thank you for your pull request. It is already possible to add the shipping address to a PaymentRequest. There is a `PayPalPaymentRequest` that has a `AddressObject` that contains all the needed properties. For example:
```
var payPalPaymentRequest = new PayPalPaymentRequest() {
                ShippingAddress = new AddressObject() {
                    City = "Rotterdam",
                    // etc
                }
            };
```

**Comment by baer999** [comment]
already possible with other structure!

**Pull request closed without merging**
