### PR TITLE
Add extra response properties for bancontact

### PR DESCRIPTION
**Pull request by senneclaeskens**
Hi,

These properties will support customerName and customerAccount which are returned by Mollie if a bancontact payment happens.

Let me know if you need anything else

### CODE REVIEW

**Review by Viincenttt — APPROVED** [review]
Hi @senneclaeskens ,

Thank you for the pull request! I'll merge it and try to update the NuGet package as soon as possible. 

Kind regards,
Vincent

**Comment by senneclaeskens** [comment]
Hi @Viincenttt , 

Any idea when it will be released? Just an ETA will do.

Thanks,
Senne

**Comment by Viincenttt** [comment]
Hi Senne, 

I will release it somewhere between friday and sunday. 

Kind regards,
Vincent

**Comment by senneclaeskens** [comment]
> Hi Senne,
> 
> I will release it somewhere between friday and sunday.
> 
> Kind regards,
> Vincent

Thanks for the reply!

**Comment by senneclaeskens** [comment]
Hi @Viincenttt ,

I see that the new version is not released yet (which, of course is not a problem).
Nevertheless, we need this functionality in our application. Is there any way that I can **easily** implement this as a workaround?

Thanks
Senne

**Comment by Viincenttt** [comment]
Hi @senneclaeskens ,

I do apologize, I completely forgot to update the package this weekend. I have just released version 2.1.0.5 of the NuGet package. If you update the version, you'll find that the extra properties on bancontact payments have been added. 

Kind regards,
Vincent

**Comment by senneclaeskens** [comment]
@Viincenttt , awesome, thanks! No problem at all by the way. You have no obligations.

**Pull request merged**
