### PR TITLE
Add MealVoucher payment method

### PR DESCRIPTION
**Pull request by P-de-Jong**

### CODE REVIEW

**Comment by Viincenttt** [comment]
Hi Pim,

I don't see any information about this new payment method. When I try to create a order with the payment method MealVoucher, the Mollie API returns a error with a 500 status code. 

Do you have any more information about this payment method?

Kind regards,
Vincent

**Comment by P-de-Jong** [comment]
Hi Vincent,

Sure!
We're getting JSON errors when using our test API key. So as it turns out, Mollie is returning a new payment method. Thing is, it's not even "public" yet, and we didn't ask for it haha. Weird thing also is, we only receive it using the `resource=orders` parameter.

The only info i can find is this: https://www.mollie.com/en/payments/meal-and-eco-vouchers

This is the response we're getting from Mollie:
```json
    {
        "resource": "method",
        "id": "mealvoucher",
        "description": "Meal vouchers",
        "minimumAmount": {
          "value": "0.01",
          "currency": "EUR"
        },
        "maximumAmount": {
          "value": "100000.00",
          "currency": "EUR"
        },
        "image": {
          "size1x": "https://www.mollie.com/external/icons/payment-methods/mealvoucher.png",
          "size2x": "https://www.mollie.com/external/icons/payment-methods/mealvoucher%402x.png",
          "svg": "https://www.mollie.com/external/icons/payment-methods/mealvoucher.svg"
        },
        "status": null,
        "_links": {
          "self": {
            "href": "https://api.mollie.com/v2/methods/mealvoucher",
            "type": "application/hal+json"
          }
        }
      }
```

**Comment by Viincenttt** [comment]
Alright, thanks. I'll merge it as it seems like it will be a payment method that Mollie is going to add soon.

**Comment by P-de-Jong** [comment]
Awesome, thanks!
This helps us a lot :)

**Pull request merged**
