### PR TITLE
Connect Api And Profiles Api

### PR DESCRIPTION
**Pull request by lgoudriaan**
Hi,

I created the [Connect Api](https://www.mollie.com/nl/docs/reference/oauth/authorize)
And [Profiles Api](https://www.mollie.com/nl/docs/reference/profiles/create)

Can you take a look at this?

### CODE REVIEW

**Comment by lgoudriaan** [comment]
Any feedback?

**Comment by Viincenttt** [comment]
Hi lgoudriaan,

Sorry for not responding sooner, but I've been on a holiday :) Thanks alot for your awesome contribution. After i've done some more testing I'll release a new version of the API :D 

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Hi lgoudriaan, 

Some feedback: 
1. I haven't used the Profile and Connect Api's before, so sorry if I am asking silly questions about them. I can't get the get the ProfileClient you wrote to work. I keep getting a Unauthorized request response. Is there a setting in the Mollie dashboard I have to enable for it to work? 
2. What's the best way for me to test the connect client API? 

Kind regards,
Vincent

**Comment by lgoudriaan** [comment]
No problem, I hope you had a great holiday!

The ProfileClient only works with Oauth tokens. So first you will need to register an app first in settings > apps.
After that you will have a client Id and client secret wich you can use in the Connect client to create a link to connect your account with the app. Keep in mind that you need to provide the correct Scopes.
After logging in with the link you will receive an authorization code, which you can use in the GetAccessTokenAsync method. This willl get you an oauth access token wich you can use in the profilesClient.

I will make a PR to check if the developer is providing the correct api key or accesstoken so it's easier to understand why it returns unauthorized.

Btw do you also think we should create constants for the scopes? https://www.mollie.com/nl/docs/oauth/permissions

**Pull request merged**
