### PR TITLE
implemented reseller client and allow retrieve customer payments by a…

### PR DESCRIPTION
**Pull request by wouterroos**
implemented basic reseller client and allow retrieve customer payments by adding payments link to customer response

### CODE REVIEW

**Comment by wouterroos** [comment]
related to #69 and #86

**Comment by wouterroos** [comment]
Please note that this is code is published 'as is'. Feedback is welcome.

**Comment by kurtwilbies** [comment]
In general, there is nothing really wrong with this code. Does the code works well in the real world? Furthermore, does it work well with viincenttt code (is all code, also generics, really needed)?

**Comment by Viincenttt** [comment]
I never looked at the Reseller API before. To be honest I find it very strange that Mollie decided to use XML for this API, while they are using JSON for all the other API's. I also noticed the authentication method of the Reseller API is different from the other API's. This makes it very difficult to re-use code from the other API's, such as the BaseMollieClient class. 

Because of this, there is some code duplication in the pull request. For example: BaseMollieClient (master) and BaseClient (pull request) are very similar. I also noticed that there are now two MollieApiException classes in the project, which is confusing. 

There is nothing wrong with the code in your pull request, but I do feel we need to find a way to make the different type of API's share more of the same codebase.

**Comment by wouterroos** [comment]
Agreed, there is some work to be done. The duplicate code is a result of us writing the Reseller API code whilst using the Mollie API NuGet package for the other APIs. I then merged the two codebases to create this PR but didn't have the time to solve any duplicates and other issues. There are also a fair amount of operations not yet implemented as we didn't need them for our project. As for the XML vs JSON thing, we've had a chat with the guys over at Mollie and they said the Reseller API should be considered 'v1' and that they're are working to port over the functionality of this API to a new, JSON based API. They didn't have an exact timeline for that however, so the Reseller API will be around for some time.

**Comment by kurtwilbies** [comment]
Any updates?

**Comment by Viincenttt** [comment]
The Reseller API has been deprecated:
> The Reseller API has been deprecated. Only selected partners still have access to this legacy functionality. As an alternative, we recommend using Mollie Connect and the Mollie v2 API.
Source: https://docs.mollie.com/reference/reseller-api/guides/overview

**Pull request closed without merging**
