### PR TITLE
added paypal specific properties to MandateRequest

### PR DESCRIPTION
**Pull request by markusdresch**
should probably be organized into a concrete class, similar to PaymentRequests?

### CODE REVIEW

**Comment by Viincenttt** [comment]
Thanks for the pull request. I'm going to need to dive into the Mandate API for a bit, since I haven't used it in a while. I'll get back to you!

**Comment by markusdresch** [comment]
just a note, the second commit would be a breaking change for someone using the `MandateModel` for directdebit mandates.

**Comment by Sippelberg** [comment]
Hey, could this get published? could really use that paypalBillingAgreementId.

**Comment by markusdresch** [comment]
@Sippelberg as a workaround in the meantime, you can simply inherit a class from MandateRequest and add your required properties.

**Comment by Sippelberg** [comment]
Hey @markusdresch, thanks for the workaround!

**Comment by Viincenttt** [comment]
Sorry for taking so long. I completely forgot about this PR.

**Comment by Viincenttt** [comment]
This is now live in 2.1.0.4: https://github.com/Viincenttt/MollieApi/releases/tag/2.1.0.4

Thanks @markusdresch !

Kind regards,
Vincent

**Pull request merged**
