### PR TITLE
Added Customer API and implemented new recurring payment method

### PR DESCRIPTION
**Pull request by Leonm91**
I've added a customer API.
Mollie introduced payment subscription where this entity is needed.

Coming up:

- Mandate API
- Recurring payments

### CODE REVIEW

**Comment by Viincenttt** [comment]
Hi,

Looks great, thanks for the update. It looks like you forgot to commit the views in the /Views/Mandate/ folder of the WebApplicationExample project. Once you have added it I will take another look.

Vincent

**Comment by Leonm91** [comment]
Added! Somehow this file was ignored.

**Comment by Viincenttt** [comment]
Hi Leon,

Thanks, I have merged your changes back to the master. I have also added some unit tests for the Customer and the Mandate API, did some code-formatting changes and slightly refactored some of the code. 

I'll do some more testing later and then I will create a new release. 

Thanks again,
Vincent

**Comment by Leonm91** [comment]
Hi Vincent,

Thank you too! 

Leon

**Pull request merged**
