### PR TITLE
Fix map payment response objects to subclasses

### PR DESCRIPTION
**Pull request by tstrooba**

### CODE REVIEW

**Comment by Viincenttt** [comment]
Hi tstrooba, 

Could you provide a brief description of this fix? In which situations did the ListResponse subclasses fail to serialize?

Kind regards,
Vincent

**Comment by Viincenttt** [comment]
Hi Tim,

Thanks for the explanation. Don't worry about forking/pull requests, you are doing fine and I am always happy when other people take the time to contribute to open source projects. Could you set the target branch for your pull request to to the development-2.0.3.0 branch? See screenshot for details on how to do this:
Switching branch

**Comment by tstrooba** [comment]
Done.

**Comment by Viincenttt** [comment]
That was fast! :D

**Pull request merged**
