### PR TITLE
Added mocking possibility to MollieClient for unit testing

### PR DESCRIPTION
**Pull request by stephanonline**
Adds the possibility to mock the MollieClient class for unit testing.

### CODE REVIEW

**Comment by Viincenttt** [comment]
Hi Stephan,

Thank you for creating this pull request. I would prefer if you'd would simply create an interface for the mollie client instead of making every method virtual. Making a method virtual implies that I intended to let users override this method, which isn't really the case. 

An interface does not change the beviour of the MollieClient class, so I would prefer an interface. 

Kind regards,
Vincent

**Comment by stephanonline** [comment]
Ok, I removed the virtuals and replaced it with an interface. I have broken down the IMollieClient into multiple interfaces for each segment.

**Comment by Viincenttt** [comment]
Great thanks! I'll check it out this weekend

**Comment by Viincenttt** [comment]
Hi stephanonline, 

I am sorry about the delay, I have been quite busy lately. I have merged the pull request and created a new version. Update your nuget package to use your new interfaces. 

Once again: Sorry for the delay and thank you very much for your contribution! 

Kind regards,
Vincent

**Pull request merged**
